CREATE TABLE NOTE (
  ID UUID PRIMARY KEY,
  CREATOR VARCHAR(100) NOT NULL,
  NOTE TEXT NOT NULL,
  CREATED_AT TIMESTAMPTZ NOT NULL,
  UPDATED_AT TIMESTAMPTZ NOT NULL,
  VERSION INTEGER NOT NULL
);

CREATE INDEX idx_notes_id_u ON NOTE(id);
CREATE INDEX idx_notes_creator ON NOTE(creator);
